update public.badges set description = 'Você cadastrou uma Costela-de-adão no seu jardim e suas folhas recortadas entraram pra coleção.' where id = 'monstera-deliciosa';
update public.badges set description = 'Você cadastrou uma Jiboia no seu jardim, a queridinha que cresce em qualquer cantinho.' where id = 'epipremnum-aureum';
update public.badges set description = 'Você cadastrou uma Espada-de-são-jorge no seu jardim, a protetora clássica de todo lar.' where id = 'dracaena-trifasciata';
update public.badges set description = 'Você cadastrou um Singônio no seu jardim e suas folhinhas em flecha se juntaram à turma.' where id = 'syngonium-podophyllum';
update public.badges set description = 'Você cadastrou uma Comigo-ninguém-pode no seu jardim, com respeito às suas folhas espertas.' where id = 'dieffenbachia-seguine';
update public.badges set description = 'Você cadastrou uma Areca-bambu no seu jardim e deu um ar tropical à coleção.' where id = 'chrysalidocarpus-lutescens';
update public.badges set description = 'Você cadastrou uma Palmeira-ráfia no seu jardim, elegante como o nome sugere.' where id = 'chamaedorea-elegans';
update public.badges set description = 'Você cadastrou uma Costela-de-adão mini no seu jardim, a versão compacta que cabe em qualquer canto.' where id = 'rhaphidophora-tetrasperma';
update public.badges set description = 'Você cadastrou uma Jiboia-prateada no seu jardim e seu brilho metálico entrou pra coleção.' where id = 'scindapsus-aureus';
update public.badges set description = 'Você cadastrou um Trevo-roxo no seu jardim, com aquelas folhinhas que dançam à noite.' where id = 'oxalis-triangularis';
update public.badges set description = 'Você cadastrou uma Haworthia-zebra no seu jardim, listrada e cheia de estilo.' where id = 'haworthia-attenuata';
update public.badges set description = 'Você cadastrou uma Pata-de-elefante no seu jardim, com o tronco guardando água pros dias difíceis.' where id = 'beaucarnea-recurvata';
update public.badges set description = 'Você cadastrou uma Agave no seu jardim, resistente e cheia de personalidade.' where id = 'agave-americana';
update public.badges set description = 'Você cadastrou uma Onze-horas no seu jardim, fácil de cuidar e sempre verdinha.' where id = 'portulacaria-afra';
update public.badges set description = 'Você cadastrou uma Rosa-do-deserto no seu jardim, com flores lindas e tronco cheio de charme.' where id = 'adenium-obesum';
update public.badges set description = 'Você cadastrou um Hibisco no seu jardim e trouxe flores grandes e coloridas pra coleção.' where id = 'hibiscus-rosa-sinensis';
update public.badges set description = 'Você cadastrou uma Bromélia no seu jardim, com aquele coração colorido no centro.' where id = 'guzmania-lingulata';
update public.badges set description = 'Você cadastrou um Cacto-bola no seu jardim, coloridinho e sem espinhos ameaçadores.' where id = 'gymnocalycium-mihanovichii';
update public.badges set description = 'Você cadastrou um Cacto-coluna no seu jardim, com os espinhos dourados brilhando.' where id = 'mammillaria-elongata';
update public.badges set description = 'Você cadastrou uma Dionéia no seu jardim, a carnívora mais fofa da coleção.' where id = 'dionaea-muscipula';
